import {Footer,Masthead} from "@/components/editorial";
export const metadata={title:"Submit a record",description:"Submit corrections, documentary leads, rights notes, or evidence-led pitches to Obscured Records."};
const items=[
  {n:"01",h:"What belongs here",p:"Corrections, primary-source leads, rights or attribution notes, and real events with a documentary trail that were ignored, flattened into trivia or never explained with enough care."},
  {n:"02",h:"What to send",p:"Start the subject with Correction, Source, Rights or Pitch. Include the record or proposed story, direct source links, what you believe is missing, and how the editor can follow up."},
  {n:"03",h:"Pitch guidelines",p:"In 300–500 words: explain what happened, what is genuinely overlooked, the sources you can access and why the story matters beyond novelty. A pitch is not treated as accepted until the editor explicitly confirms it."},
  {n:"04",h:"Fact checking",p:"Every central claim needs a traceable source. State uncertainty plainly. Separate evidence from inference, and never sacrifice accuracy for drama."}
];
export default function Submit(){return <main><Masthead/><section className="text-page submit-page"><span>Open desk / Source notes</span><h1>Submit a<br/>record.</h1><p className="intro">Obscured Records is currently written and edited by Ryan Gomez. Leads, primary documents, corrections, rights notes and carefully developed guest pitches are welcome.</p><div className="guidelines">{items.map(x=><article key={x.n}><span>{x.n}</span><h2>{x.h}</h2><p>{x.p}</p></article>)}</div><div className="submit-contact"><span>Direct line to the editor</span><h2>Send the record, source links and your contact details to</h2><a href="mailto:ryangomez.hsl@gmail.com?subject=Obscured%20Records%20submission">ryangomez.hsl@gmail.com</a><p>Please do not send confidential material by ordinary email. The current intake route is email-only; publication, contributor status or acceptance is never implied by receipt.</p></div></section><Footer/></main>}
